name: "CI: Prettier"

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - cf-pages
  schedule:
    - cron: "30 09 * * *"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prettier Action
        uses: creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0 # v4.6
        with:
          prettier_options: "'**/*.{js,ts,mjs,md,cjs,json,yml,html,css,less,sass}' --write"